server:
  port: 8091

spring: 
  application:  
    name: customer #指定服务名  
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8888/eureka/
  instance: 
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1

management:
  security:
    enabled: false  #是否开启actuator安全认证
